<?php
/**
 * index
 *
 * @copyright Copyright © 2020 Landofcoder. All rights reserved.
 * @author    landofcoder@gmail.com
 */

?>


<button class="hellojs" style="padding: 50px">load</button>
<p  id="text">hieu <b>dep trai</b></p>
<input id="nhap" type="text">
<p id="call-ajax"><p/>

<p id="trave"></p>
<script type="text/x-magento-init" >
    {
        "*":{
            "Lof_HieuStudentManage/js/student":{}
        }
    }
</script>